//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UtMsg
{
    [Serializable]
    public class GetFloat32sRequest : Message
    {
        public const string k_RosMessageName = "ut_msg/GetFloat32s";
        public override string RosMessageName => k_RosMessageName;


        public GetFloat32sRequest()
        {
        }
        public static GetFloat32sRequest Deserialize(MessageDeserializer deserializer) => new GetFloat32sRequest(deserializer);

        private GetFloat32sRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetFloat32sRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
