//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UtMsg
{
    [Serializable]
    public class GetFloat32sResponse : Message
    {
        public const string k_RosMessageName = "ut_msg/GetFloat32s";
        public override string RosMessageName => k_RosMessageName;

        //  ret is 0: successful  -3:disconnect  other:have error
        //  Service name: ut_msg/srv/get_joint_actual_pos
        //  response: get arm gripper actual joints [joint1,joint2,joint3,joint4,joint5,joint6] uint is rad.
        public short ret;
        public float[] data;

        public GetFloat32sResponse()
        {
            this.ret = 0;
            this.data = new float[0];
        }

        public GetFloat32sResponse(short ret, float[] data)
        {
            this.ret = ret;
            this.data = data;
        }

        public static GetFloat32sResponse Deserialize(MessageDeserializer deserializer) => new GetFloat32sResponse(deserializer);

        private GetFloat32sResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ret);
            deserializer.Read(out this.data, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ret);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "GetFloat32sResponse: " +
            "\nret: " + ret.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
