//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UtMsg
{
    [Serializable]
    public class Utra6TrajectoryMsg : Message
    {
        public const string k_RosMessageName = "ut_msg/Utra6Trajectory";
        public override string RosMessageName => k_RosMessageName;

        public Trajectory.JointTrajectoryMsg trajectory;

        public Utra6TrajectoryMsg()
        {
            this.trajectory = new Trajectory.JointTrajectoryMsg();
        }

        public Utra6TrajectoryMsg(Trajectory.JointTrajectoryMsg trajectory)
        {
            this.trajectory = trajectory;
        }

        public static Utra6TrajectoryMsg Deserialize(MessageDeserializer deserializer) => new Utra6TrajectoryMsg(deserializer);

        private Utra6TrajectoryMsg(MessageDeserializer deserializer)
        {
            this.trajectory = Trajectory.JointTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "Utra6TrajectoryMsg: " +
            "\ntrajectory: " + trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
